import arrows from "./arrows";
import basic from "./basic";
import flowchart from "./flowchart";
import floorplan from "./floorplan";
import cabinets from "./cabinets";
import fluid_power from "./fluid_power";
import kubernetes from "./kubernetes";
// import salesforce from "./salesforce";
// import aws3 from "./aws3";
import aws3d from "./aws3d";
// import aws4 from "./aws4";
import azure from "./azure";
import pid_agitators from "./pid/agitators";
import pid_apparatus_elements from "./pid/apparatus_elements";
import pid_centrifuges from "./pid/centrifuges";
import pid_compressors from "./pid/compressors";
import pid_compressors_iso from "./pid/compressors_iso";
import pid_crushers_grinding from "./pid/crushers_grinding";
import pid_driers from "./pid/driers";
import pid_engines from "./pid/engines";
import pid_feeders from "./pid/feeders";
import pid_filters from "./pid/filters";
import pid_fittings from "./pid/fittings";
import pid_flow_sensors from "./pid/flow_sensors";
import pid_heat_exchangers from "./pid/heat_exchangers";
import pid_instruments from "./pid/instruments";
import pid_misc from "./pid/misc";
import pid_mixers from "./pid/mixers";
import pid_piping from "./pid/piping";
import pid_pumps from "./pid/pumps";
import pid_pumps_din from "./pid/pumps_din";
import pid_pumps_iso from "./pid/pumps_iso";
import pid_separators from "./pid/separators";
import pid_shaping_machines from "./pid/shaping_machines";
import pid_valves from "./pid/valves";
import pid_vessels from "./pid/vessels";

// import mscae_cloud from "./mscae/cloud";
import mscae_deprecated from "./mscae/deprecated";
import mscae_enterprise from "./mscae/enterprise";
import mscae_general_symbols from "./mscae/general_symbols";
import mscae_general from "./mscae/general";
import mscae_intune from "./mscae/intune";
import mscae_oms from "./mscae/oms";
import mscae_opsmanager from "./mscae/opsmanager";
import mscae_other from "./mscae/other";
import mscae_system_center from "./mscae/system_center";
import mscae_vm from "./mscae/vm";

import signs_animals from "./signs/animals";
import signs_food from "./signs/food";
import signs_healthcare from "./signs/healthcare";
import signs_nature from "./signs/nature";
import signs_people from "./signs/people";
import signs_safety from "./signs/safety";
import signs_science from "./signs/science";
import signs_sports from "./signs/sports";
import signs_tech from "./signs/tech";
import signs_transportation from "./signs/transportation";
import signs_travel from "./signs/travel";

import bpmn from "./bpmn";
import Credit_Card_128x128 from "./clipart/Credit_Card_128x128.js";
import Database_128x128 from "./clipart/Database_128x128";
import Doctor1_128x128 from "./clipart/Doctor1_128x128";
import Earth_globe_128x128 from "./clipart/Earth_globe_128x128";
import Email_128x128 from "./clipart/Email_128x128";
import Empty_Folder_128x128 from "./clipart/Empty_Folder_128x128";
import Firewall_02_128x128 from "./clipart/Firewall_02_128x128";
import Full_Folder_128x128 from "./clipart/Full_Folder_128x128";
import Gear_128x128 from "./clipart/Gear_128x128";
import Graph_128x128 from "./clipart/Graph_128x128";
import iMac_128x128 from "./clipart/iMac_128x128";
import iPad_128x128 from "./clipart/iPad_128x128";
import Laptop_128x128 from "./clipart/Laptop_128x128";
import Lock_128x128 from "./clipart/Lock_128x128";
import MacBook_128x128 from "./clipart/MacBook_128x128";
import Monitor_Tower_128x128 from "./clipart/Monitor_Tower_128x128";
import Piggy_Bank_128x128 from "./clipart/Piggy_Bank_128x128";
import Pilot1_128x128 from "./clipart/Pilot1_128x128";
import Printer_128x128 from "./clipart/Printer_128x128";
import Router_Icon_128x128 from "./clipart/Router_Icon_128x128";
import Safe_128x128 from "./clipart/Safe_128x128";
import Security1_128x128 from "./clipart/Security1_128x128";
import Server_Tower_128x128 from "./clipart/Server_Tower_128x128";
import Shopping_Cart_128x128 from "./clipart/Shopping_Cart_128x128";
import Software_128x128 from "./clipart/Software_128x128";
import Soldier1_128x128 from "./clipart/Soldier1_128x128";
import Suit1_128x128 from "./clipart/Suit1_128x128";
import Suit2_128x128 from "./clipart/Suit2_128x128";
import Suit3_128x128 from "./clipart/Suit3_128x128";
import Tech1_128x128 from "./clipart/Tech1_128x128";
import Telesales1_128x128 from "./clipart/Telesales1_128x128";
import Virtual_Machine_128x128 from "./clipart/Virtual_Machine_128x128";
import Virus_128x128 from "./clipart/Virus_128x128";
import Wireless_Router_N_128x128 from "./clipart/Wireless_Router_N_128x128";
import Worker1_128x128 from "./clipart/Worker1_128x128";
import Workstation_128x128 from "./clipart/Workstation_128x128";
import logic_gates from "./electrical/logic_gates.xml.js";
import iec_logic_gates from "./electrical/iec_logic_gates.xml.js";
import abstract from "./electrical/abstract.xml.js";
import capacitors from "./electrical/capacitors.xml.js";
import diodes from "./electrical/diodes.xml.js";
import electroMechanical from "./electrical/electro-mechanical.xml.js";
import iec417 from "./electrical/iec417.xml.js";
import inductors from "./electrical/inductors.xml.js";
import instruments from "./electrical/instruments.xml.js";
import miscellaneous from "./electrical/miscellaneous.xml.js";
import mosfets1 from "./electrical/mosfets1.xml.js";
import mosfets2 from "./electrical/mosfets2.xml.js";
import op_amps from "./electrical/op_amps.xml.js";
import plc_ladder from "./electrical/plc_ladder.xml.js";
import power_semiconductors from "./electrical/power_semiconductors.xml.js";
import radio from "./electrical/radio.xml.js";
import resistors from "./electrical/resistors.xml.js";
import rot_mech from "./electrical/rot_mech.xml.js";
import signal_sources from "./electrical/signal_sources.xml.js";
import thermionic_devices from "./electrical/thermionic_devices.xml.js";
import transistors from "./electrical/transistors.xml.js";
import transmission from "./electrical/transmission.xml.js";
import waveforms from "./electrical/waveforms.xml.js";

const XML = ".xml";
const PNG = ".png";
const dict = {};
export const getStencil = function(name){
    return dict[name];
};

dict["electrical/logic_gates" + XML] = logic_gates;
dict["electrical/iec_logic_gates" + XML] = iec_logic_gates;
dict["electrical/abstract" + XML] = abstract;
dict["electrical/capacitors" + XML] = capacitors;
dict["electrical/diodes" + XML] = diodes;
dict["electrical/electro-mechanical" + XML] = electroMechanical;
dict["electrical/iec417" + XML] = iec417;
dict["electrical/inductors" + XML] = inductors;
dict["electrical/instruments" + XML] = instruments;
dict["electrical/miscellaneous" + XML] = miscellaneous;
dict["electrical/mosfets1" + XML] = mosfets1;
dict["electrical/mosfets2" + XML] = mosfets2;
dict["electrical/op_amps" + XML] = op_amps;
dict["electrical/plc_ladder" + XML] = plc_ladder;
dict["electrical/power_semiconductors" + XML] = power_semiconductors;
dict["electrical/radio" + XML] = radio;
dict["electrical/resistors" + XML] = resistors;
dict["electrical/rot_mech" + XML] = rot_mech;
dict["electrical/signal_sources" + XML] = signal_sources;
dict["electrical/thermionic_devices" + XML] = thermionic_devices;
dict["electrical/transistors" + XML] = transistors;
dict["electrical/transmission" + XML] = transmission;
dict["electrical/waveforms" + XML] = waveforms;

// dict["mscae/cloud" + XML] = mscae_cloud;
dict["mscae/deprecated" + XML] = mscae_deprecated;
dict["mscae/enterprise" + XML] = mscae_enterprise;
dict["mscae/general_symbols" + XML] = mscae_general_symbols;
dict["mscae/general" + XML] = mscae_general;
dict["mscae/intune" + XML] = mscae_intune;
dict["mscae/oms" + XML] = mscae_oms;
dict["mscae/opsmanager" + XML] = mscae_opsmanager;
dict["mscae/other" + XML] = mscae_other;
dict["mscae/system_center" + XML] = mscae_system_center;
dict["mscae/vm" + XML] = mscae_vm;


dict["floorplan" + XML] = floorplan;
dict["cabinets" + XML] = cabinets;
dict["arrows" + XML] = arrows;
dict["basic" + XML] = basic;
dict["flowchart" + XML] = flowchart;
dict["fluid_power" + XML] = fluid_power;
dict["kubernetes" + XML] = kubernetes;
// dict["salesforce" + XML] = salesforce;
// dict["aws3" + XML] = aws3;
dict["aws3d" + XML] = aws3d;
// dict["aws4" + XML] = aws4;
dict["azure" + XML] = azure;
dict["bpmn" + XML] = bpmn;
dict['pid/misc.xml'] = pid_misc;
dict['pid/agitators.xml'] = pid_agitators;
dict['pid/apparatus_elements.xml'] = pid_apparatus_elements;
dict['pid/centrifuges.xml'] = pid_centrifuges;
dict['pid/compressors.xml'] = pid_compressors;
dict['pid/compressors_iso.xml'] = pid_compressors_iso;
dict['pid/crushers_grinding.xml'] = pid_crushers_grinding;
dict['pid/driers.xml'] = pid_driers;
dict['pid/engines.xml'] = pid_engines;
dict['pid/feeders.xml'] = pid_feeders;
dict['pid/filters.xml'] = pid_filters;
dict['pid/fittings.xml'] = pid_fittings;
dict['pid/flow_sensors.xml'] = pid_flow_sensors;
dict['pid/heat_exchangers.xml'] = pid_heat_exchangers;
dict['pid/instruments.xml'] = pid_instruments;
dict['pid/mixers.xml'] = pid_mixers;
dict['pid/piping.xml'] = pid_piping;
dict['pid/pumps.xml'] = pid_pumps;
dict['pid/pumps_din.xml'] = pid_pumps_din;
dict['pid/pumps_iso.xml'] = pid_pumps_iso;
dict['pid/separators.xml'] = pid_separators;
dict['pid/shaping_machines.xml'] = pid_shaping_machines;
dict['pid/valves.xml'] = pid_valves;
dict['pid/vessels.xml'] = pid_vessels;

dict['signs/animals.xml'] = signs_animals;
dict['signs/food.xml'] = signs_food;
dict['signs/healthcare.xml'] = signs_healthcare;
dict['signs/nature.xml'] = signs_nature;
dict['signs/people.xml'] = signs_people;
dict['signs/safety.xml'] = signs_safety;
dict['signs/science.xml'] = signs_science;
dict['signs/sports.xml'] = signs_sports;
dict['signs/tech.xml'] = signs_tech;
dict['signs/transportation.xml'] = signs_transportation;
dict['signs/travel.xml'] = signs_travel;

dict["Credit_Card_128x128" + PNG] = Credit_Card_128x128;
dict["Database_128x128" + PNG] = Database_128x128;
dict["Doctor1_128x128" + PNG] = Doctor1_128x128;
dict["Earth_globe_128x128" + PNG] = Earth_globe_128x128;
dict["Email_128x128" + PNG] = Email_128x128;
dict["Empty_Folder_128x128" + PNG] = Empty_Folder_128x128;
dict["Firewall_02_128x128" + PNG] = Firewall_02_128x128;
dict["Full_Folder_128x128" + PNG] = Full_Folder_128x128;
dict["Gear_128x128" + PNG] = Gear_128x128;
dict["Graph_128x128" + PNG] = Graph_128x128;
dict["iMac_128x128" + PNG] = iMac_128x128;
dict["iPad_128x128" + PNG] = iPad_128x128;
dict["Laptop_128x128" + PNG] = Laptop_128x128;
dict["Lock_128x128" + PNG] = Lock_128x128;
dict["MacBook_128x128" + PNG] = MacBook_128x128;
dict["Monitor_Tower_128x128" + PNG] = Monitor_Tower_128x128;
dict["Piggy_Bank_128x128" + PNG] = Piggy_Bank_128x128;
dict["Pilot1_128x128" + PNG] = Pilot1_128x128;
dict["Printer_128x128" + PNG] = Printer_128x128;
dict["Router_Icon_128x128" + PNG] = Router_Icon_128x128;
dict["Safe_128x128" + PNG] = Safe_128x128;
dict["Security1_128x128" + PNG] = Security1_128x128;
dict["Server_Tower_128x128" + PNG] = Server_Tower_128x128;
dict["Shopping_Cart_128x128" + PNG] = Shopping_Cart_128x128;
dict["Software_128x128" + PNG] = Software_128x128;
dict["Soldier1_128x128" + PNG] = Soldier1_128x128;
dict["Suit1_128x128" + PNG] = Suit1_128x128;
dict["Suit2_128x128" + PNG] = Suit2_128x128;
dict["Suit3_128x128" + PNG] = Suit3_128x128;
dict["Tech1_128x128" + PNG] = Tech1_128x128;
dict["Telesales1_128x128" + PNG] = Telesales1_128x128;
dict["Virtual_Machine_128x128" + PNG] = Virtual_Machine_128x128;
dict["Virus_128x128" + PNG] = Virus_128x128;
dict["Wireless_Router_N_128x128" + PNG] = Wireless_Router_N_128x128;
dict["Worker1_128x128" + PNG] = Worker1_128x128;
dict["Workstation_128x128" + PNG] = Workstation_128x128;
